### ISSUE TITLE
solve captcha with circles

### ISSUE THREAD

**Issue by teliz** [skotz/cbl-js#18]
I'm trying to solve this captcha but these circles are disturbing, have any tips?
https://ibb.co/nz7QQx
https://ibb.co/kvuiCc
https://ibb.co/h7g8dH

**Comment by skotz** [comment]
All three of those have the same solution: "mtdgi"... Does that CAPTCHA return anything but that?

I'd probably look into exploiting the fact that the circles are thinner than the letters. You might try implementing an erosion filter that removes one pixel of non-background color from the top and left (effectively removing any 1 pixel wide lines and turning any 2 pixel wide lines into 1 pixel). This would take some work to implement. You could start by looking over a similar method in [my C# version of this library](https://github.com/skotz/captcha-breaking-library/blob/c7f75de37ad585c83e2f1b84d91933cc03e53270/ScottClayton.CAPTCHA/Image/Segmenter.cs#L756).

Another possible approach, albeit more complicated, would be to iterate through every possible circle dimension in the image and blot out anything that looks perfectly round. This would probably also catch any characters with a circle in the letter itself. I've seen this approach for removing lines in other CAPTCHA solving research.

Yet another random idea. The letters always appear to be in the same relative locations, so you could truncate to the smallest common bounding box and train as if the circles weren't there. Over time, the model may minimize the predictive ability of the circles.

Hope that helps. This one's a difficult one since the added noise is the same color and relatively the same size as the letters.

**Comment by teliz** [comment]
Hi, thank you very much, I'll try to follow your approach.
it helped a lot :)
