### ISSUE TITLE
Support with Node Js

### ISSUE THREAD

**Issue by paulebe** [skotz/cbl-js#22]
I have a lot of trouble in executing cbl.js on server side. any help???

**Comment by skotz** [comment]
I've not tested the library with Node since I just run it in the browser. You could check out the Quick Start Guide for instructions on how to set up a simple local server that works fine. Also note that you do need to access the page over http or https, not file:// due to CORS stuff.

https://github.com/skotz/cbl-js/blob/master/starter/quickstart.md

**Comment by skotz** [comment]
Sorry, but I currently have no plans to make this particular library work with Node,

I do have a version of this library written in C# (see my other repos), and you should be able to expose that as a service quite easily if you needed to. It's a lot more complex to learn, but it's an option.

**Comment by paulebe** [comment]
CLOSED

**Comment by mkp95** [comment]
any way to setup node js server side captcha solving like an api

**Comment by skotz** [comment]
Currently this isn't supported.
