### ISSUE TITLE
How to solve this captcha?

### ISSUE THREAD

**Issue by Elvincth** [skotz/cbl-js#23]
I tried many method it didn't work, can u help me for this? Many thanks!

![](https://i.imgur.com/i5ThC0D.jpg)

![](https://i.imgur.com/vIcgvz4.jpg)

![](https://i.imgur.com/myZihuN.jpg)

![](https://i.imgur.com/7BVeqIZ.png)

![](https://i.imgur.com/4KYNCjY.png)

![](https://i.imgur.com/N7nANdD.jpg)

**Comment by skotz** [comment]
This may be difficult to get good accuracy on since it's using upper case, lower case, and similar characters (e.g., "1" and "I" and "l").

Here's something to get you started:

```
var cbl = new CBL({
    preprocess: function(img) {
        img.debugImage("debugPreprocessed");
        img.binarize(220);
        img.debugImage("debugPreprocessed");
        img.convolute([ [1, 0, 1],
                        [0, 1, 0],
                        [1, 0, 1] ], 1/3);
        img.debugImage("debugPreprocessed");
        img.blur();
        img.debugImage("debugPreprocessed");
        img.binarize(200);
        img.debugImage("debugPreprocessed");
        img.colorRegions(40, true);
        img.debugImage("debugPreprocessed");
    },
    character_set: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
    blob_min_pixels: 50,
    blob_max_pixels: 500,
    pattern_width: 20,
    pattern_height: 20,
    allow_console_log: true,
    blob_debug: "debugSegmented"
});
```

It works pretty well. The convolution filter will remove most of the purely horizontal or vertical lines. The only image that this didn't get all the characters out of was the nW2Y image, but that's because the lines between the middle two characters were thick enough to not get removed. If you play around with the settings on more than just these 6 images, you should be able to improve the segmentation.

![segmented](https://user-images.githubusercontent.com/11474654/42975865-38283cbe-8b84-11e8-8456-b4cdcf39879e.png)

Here are the extracted letters after segmentation for all 6 images:

![trained-model](https://user-images.githubusercontent.com/11474654/42975933-99faa490-8b84-11e8-9058-03efb6d362e5.png)

And here's the model visualization after condensing and sorting:

![condensed-sorted-model](https://user-images.githubusercontent.com/11474654/42975984-d8c2fbe6-8b84-11e8-8427-39e3a014226a.PNG)

**Comment by Elvincth** [comment]
@skotz Thank!
