### ISSUE TITLE
Can you please help to solve this white lane crossed captcha?

### ISSUE THREAD

**Issue by ArthurKa** [skotz/cbl-js#55]
```js
new CBL({
  preprocess: function(img) { /* ... */ },
  blob_debug: 'debugSegmented',
  character_set: '0123456789abcdefghijklmnopqrstuvwxyz',
  blob_min_pixels: 40,
  blob_max_pixels: 100000,
  pattern_width: 24,
  pattern_height: 24,
  pattern_maintain_ratio: true,
  perceptive_colorspace: true,
});
```

```
Original
```
![Original captcha](https://user-images.githubusercontent.com/16370704/85905181-6533bb80-b813-11ea-8a72-97a896621a08.jpg)

```js
img.convolute([
  [1, 2, 1], 
  [1, 3, 1], 
  [1, 2, 1],
], 1/13);
```
![Convoluted captcha](https://user-images.githubusercontent.com/16370704/85905307-c065ae00-b813-11ea-9baa-eaf4bf32523f.png)

```js
img.binarize(200);
```
![Binarized captcha](https://user-images.githubusercontent.com/16370704/85905362-e3905d80-b813-11ea-9c76-09d35d29d090.png)

```js
img.colorRegions(10, true, 1);
```
![Color regioned captcha](https://user-images.githubusercontent.com/16370704/85905378-eab76b80-b813-11ea-8108-426ee6417315.png)

As you can see the solver recognized wrong segments cause of these white lane crossed characters.

Is there any documentation provided? Cause I found no one and just randomly substitute example options...

**Comment by skotz** [comment]
It's hard to make assumptions off one image, but this one looks like it'll be difficult to solve.

A couple of things to look out for that might help...
- If all images have the same number of characters then there's a setting you can use to always return that many characters
- If there are always 6 characters and they're always in the same place, then you can use the exact character splitting methods (the examples folder has a few examples)
- If the distortion is always the same on each image (like a letter "p" always has the exact same shape) then that'll help too, however since your image has two 6's and two p's that aren't identical I doubt this is the case.
- A possible strategy might be to either try to find the right combination of blur filters to try to get rid of the lines, or write some custom code to detect the lines (there is some line removal code in the library, but it currently isn't written to remove a line that's the same color as the background)

Good luck

**Comment by ArthurKa** [comment]
Here is more images:
![photo_2020-06-26_23-56-26](https://user-images.githubusercontent.com/16370704/85944279-48e06d80-b93e-11ea-83e5-44f5a464e129.jpg)
![photo_2020-06-26_23-56-32](https://user-images.githubusercontent.com/16370704/85944284-4da52180-b93e-11ea-8edf-fd808d5ff9f3.jpg)
![photo_2020-06-26_23-56-35](https://user-images.githubusercontent.com/16370704/85944285-50a01200-b93e-11ea-8e26-548f0bf27bf3.jpg)
![photo_2020-06-26_23-56-38](https://user-images.githubusercontent.com/16370704/85944287-5269d580-b93e-11ea-910a-92a1fd0d1830.jpg)

**Comment by ArthurKa** [comment]
Thanks anyway.
