### ISSUE TITLE
Can't seem to solve this captcha

### ISSUE THREAD

**Issue by nicolaspavlotsky** [skotz/cbl-js#59]
Hi, I'm trying to solve this captchas:

![0avp](https://user-images.githubusercontent.com/49616821/98006537-228d7b80-1dd1-11eb-83e4-a49fad82a460.gif)
![7wmv](https://user-images.githubusercontent.com/49616821/98006539-23261200-1dd1-11eb-8e73-835aaffa40da.gif)
![8hog](https://user-images.githubusercontent.com/49616821/98006540-23bea880-1dd1-11eb-98a1-adb53385bca4.gif)
![26j7](https://user-images.githubusercontent.com/49616821/98006541-23bea880-1dd1-11eb-9e7b-d8e7770942bb.gif)
![51fo](https://user-images.githubusercontent.com/49616821/98006545-24573f00-1dd1-11eb-9bdc-f255b39691d6.gif)
![56t1](https://user-images.githubusercontent.com/49616821/98006547-24573f00-1dd1-11eb-9fc5-d3a95b9245e5.gif)

Without success. Here's my config:

```
preprocess: function(img){
  img.binarize(220);
  img.blur();
  img.binarize(110);
  img.colorRegions(100);
},
character_set: "abcdefghijklmnopqrstuvwxyz0123456789",
blob_min_pixels: 50,
blob_max_pixels: 400,
pattern_width: 25,
pattern_height: 25,
allow_console_log: true,
perceptive_colorspace: true,
```

**Comment by skotz** [comment]
Since all images appear to have exactly four characters that are always in the same locations, and since the background appears to be identical across all images, you could probably get away with just using `fixed_blob_locations`.

![image](https://user-images.githubusercontent.com/11474654/98308817-9a54d500-1f8e-11eb-8e77-bbcb5f20f66d.png)

```
<div class="main">
    <div id="debugPreprocessed"></div>
    <div id="debugSegmented"></div>
    <div id="solution"></div>
    <div id="visualizeModel"></div>
</div>
<script>
    var cbl = new CBL({
        fixed_blob_locations: [
            { x1: 20, y1: 14, x2: 39, y2: 33 },
            { x1: 40, y1: 14, x2: 59, y2: 33 },
            { x1: 60, y1: 14, x2: 79, y2: 33 },
            { x1: 80, y1: 14, x2: 99, y2: 33 }
        ],
        character_set: "abcdefghijklmnopqrstuvwxyz0123456789",
        blob_min_pixels: 50,
        blob_max_pixels: 400,
        pattern_width: 20,
        pattern_height: 20,
        allow_console_log: true,
        perceptive_colorspace: true,
        exact_characters: 4,
        blob_console_debug: true,
        blob_debug: "debugSegmented"
    });

    cbl.train("0avp.jpg");
    cbl.train("7wmv.jpg");
    cbl.train("8hog.jpg");
    cbl.train("26j7.jpg");
    cbl.train("51fo.jpg");
    cbl.train("56t1.jpg");

    var saveModel = function() {
        cbl.condenseModel();
        cbl.sortModel();
        cbl.visualizeModel("visualizeModel");
        cbl.saveModel();
    }
</script>
```

The serialized model (created by calling `saveModel()` after training) is really clean. You'll just need to make sure you train on enough sample images to cover all the characters.

![image](https://user-images.githubusercontent.com/11474654/98309122-4c8c9c80-1f8f-11eb-8a81-08ad63ac3745.png)

**Comment by nicolaspavlotsky** [comment]
Thanks!! You're a life saver!
